# Generated by Django 6.0.8 on 2026-09-07 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RecurrenceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "interval",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Repeat every N days/weeks."
                    ),
                ),
                (
                    "weekdays",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated weekday numbers (0=Monday .. 6=Sunday) used when frequency is 'custom'. Empty otherwise.",
                        max_length=20,
                    ),
                ),
                (
                    "next_rotation_position",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Position in the rotation order whose turn is next.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Child",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "weekly_earning_limit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional weekly earning cap. NULL means no limit set.",
                        max_digits=7,
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("weekly_earning_limit__isnull", True),
                            ("weekly_earning_limit__gte", 0),
                            _connector="OR",
                        ),
                        name="child_weekly_earning_limit_non_negative",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Chore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("kitchen", "Kitchen"),
                            ("laundry", "Laundry"),
                            ("outdoors", "Outdoors"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("normal", "Normal"), ("urgent", "Urgent")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("claimed", "Claimed"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("approved", "Approved"),
                            ("returned", "Returned"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reward_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cash reward. NULL means an unpaid chore.",
                        max_digits=7,
                        null=True,
                    ),
                ),
                (
                    "is_shared",
                    models.BooleanField(
                        default=False, help_text="Any child may claim this chore."
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Most recent reason a parent returned this chore.",
                    ),
                ),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_child",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL means unassigned / available.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chores",
                        to="chores.child",
                    ),
                ),
                (
                    "recurrence_rule",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL means a one-off chore.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chores",
                        to="chores.recurrencerule",
                    ),
                ),
            ],
            options={
                "ordering": [
                    models.Case(
                        models.When(priority="urgent", then=models.Value(0)),
                        default=models.Value(1),
                        output_field=models.IntegerField(),
                    ),
                    models.OrderBy(models.F("due_at"), nulls_last=True),
                    "id",
                ],
            },
        ),
        migrations.CreateModel(
            name="RotationSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotation_slots",
                        to="chores.child",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rotation_slots",
                        to="chores.recurrencerule",
                    ),
                ),
            ],
            options={
                "ordering": ["rule_id", "position"],
            },
        ),
        migrations.CreateModel(
            name="ChoreRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chore_requests",
                        to="chores.child",
                    ),
                ),
                (
                    "resulting_chore",
                    models.ForeignKey(
                        blank=True,
                        help_text="The chore a parent created from this request, once accepted.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chores.chore",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status"], name="chore_request_status_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("paid_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="chores.child",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_on", "-id"],
                "indexes": [
                    models.Index(
                        fields=["child", "paid_on"], name="payout_child_date_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="payout_amount_positive",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="chore",
            index=models.Index(fields=["status"], name="chore_status_idx"),
        ),
        migrations.AddIndex(
            model_name="chore",
            index=models.Index(fields=["due_at"], name="chore_due_at_idx"),
        ),
        migrations.AddIndex(
            model_name="chore",
            index=models.Index(
                fields=["assigned_child", "status"], name="chore_child_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chore",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reward_amount__isnull", True),
                    ("reward_amount__gte", 0),
                    _connector="OR",
                ),
                name="chore_reward_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="rotationslot",
            constraint=models.UniqueConstraint(
                fields=("rule", "position"), name="rotation_slot_unique_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="rotationslot",
            constraint=models.UniqueConstraint(
                fields=("rule", "child"), name="rotation_slot_unique_child"
            ),
        ),
    ]
