# Generated by Django 6.0.8 on 2026-09-07 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chore",
            name="generated_from",
            field=models.ForeignKey(
                blank=True,
                help_text="The previous occurrence that generated this recurring chore.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_occurrences",
                to="chores.chore",
            ),
        ),
        migrations.AddConstraint(
            model_name="chore",
            constraint=models.UniqueConstraint(
                condition=models.Q(("generated_from__isnull", False)),
                fields=("generated_from",),
                name="chore_one_next_occurrence",
            ),
        ),
    ]
