# Generated by Django 6.0.8 on 2026-09-08 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0002_chore_generated_from_chore_chore_one_next_occurrence"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoreEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="The state machine action that was applied.",
                        max_length=20,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("claimed", "Claimed"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("approved", "Approved"),
                            ("returned", "Returned"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("claimed", "Claimed"),
                            ("awaiting_approval", "Awaiting approval"),
                            ("approved", "Approved"),
                            ("returned", "Returned"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "actor_mode",
                    models.CharField(
                        choices=[
                            ("parent", "Parent"),
                            ("kid", "Kid"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="The rejection reason for a reject, empty otherwise.",
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "acting_child",
                    models.ForeignKey(
                        blank=True,
                        help_text="NULL for parent and system actions.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chore_events",
                        to="chores.child",
                    ),
                ),
                (
                    "chore",
                    models.ForeignKey(
                        help_text="The chore this happened to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="chores.chore",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["chore", "occurred_at"], name="chore_event_time_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("from_status", ""), _negated=True),
                        name="chore_event_from_status_set",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("to_status", ""), _negated=True),
                        name="chore_event_to_status_set",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("actor_mode", ""), _negated=True),
                        name="chore_event_actor_mode_set",
                    ),
                ],
            },
        ),
    ]
