# Generated by Django 6.0.8 on 2026-09-08 03:37

import django.db.models.deletion
from django.db import migrations, models


LEGACY_CLAIM_STATUSES = {"claimed", "awaiting_approval", "approved", "returned"}


def copy_legacy_claims(apps, schema_editor):
    Chore = apps.get_model("chores", "Chore")
    ChoreClaim = apps.get_model("chores", "ChoreClaim")
    for chore in Chore.objects.filter(
        status__in=LEGACY_CLAIM_STATUSES,
        assigned_child__isnull=False,
    ).iterator():
        ChoreClaim.objects.create(
            chore_id=chore.pk,
            child_id=chore.assigned_child_id,
            claimed_at=chore.claimed_at or chore.created_at,
            completed_at=chore.completed_at,
            reward_share=chore.reward_amount if chore.status == "approved" else None,
        )


def remove_legacy_claims(apps, schema_editor):
    apps.get_model("chores", "ChoreClaim").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chores", "0003_choreevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChoreClaim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("claimed_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reward_share",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="chores.child",
                    ),
                ),
                (
                    "chore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="chores.chore",
                    ),
                ),
            ],
            options={
                "ordering": ["claimed_at", "id"],
                "indexes": [models.Index(fields=["child"], name="claim_child_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("chore", "child"), name="chore_claim_unique_child"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reward_share__isnull", True),
                            ("reward_share__gte", 0),
                            _connector="OR",
                        ),
                        name="chore_claim_reward_non_negative",
                    ),
                ],
            },
        ),
        migrations.RunPython(copy_legacy_claims, remove_legacy_claims),
    ]
